version: '3.1'
services:
  my-app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PWD: supersecret

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersecret

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecret
      ME_CONFIG_MONGODB_SERVER: mongodb 
    depends_on:
      - "mongodb"


